project: 
  name: "monodepth"
  experiment: "exp1"
  version: "1.0"

dataset:
  name: "KITTI"
  path: "./data/raw"
  
transforms:
  input_heigh: 192
  input_width: 640
  color_jitter:
    brightness: 0.5
    contrast: 0.3
    saturation: 0.2
    hue: 0.3

model:
  encoder: "resnet50"

training:
  epoch: 50
  optimizer: "Adam"
  batch_size: 8
  lr: 0.0001
  early_stoppding: True

logging:
  log_frequency: 10
  checkpoint_path: "./checkpoint/resnet50_192x640"

evaluation:
  checkpoint_path: "./checkpoint/resnet50_192x640/best"